[package]
name = "payload"
version = "0.1.0"
edition = "2021"
target = "x86_64-pc-windows-gnu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.14", features = ["blocking"]}
winapi = "0.3.9"